### ISSUE TITLE
bug in class Mesh

### ISSUE THREAD

**Issue by b1ueb1ues** [K0lb3/UnityPy#1]
File "UnityPy/classes/Mesh.py", line 423, in ProcessData
    if hasattr(self, 'm_StreamData') and self.m_StreamData.get('path'):
AttributeError: 'StreamingInfo' object has no attribute 'get'

should be self.m_StreamData.path

**Comment by K0lb3** [comment]
Sorry for the late response.

The [latest commit](https://github.com/K0lb3/UnityPy/commit/65f316826e1e079f3e2292b70e86eb5576bfa700) should have fixed the issue.
