### ISSUE TITLE
Sprite won't generate image

### ISSUE THREAD

**Issue by RandomUserrrr** [K0lb3/UnityPy#107]
**Code**
```py
env = UnityPy.load('path/to/bundle')
for obj in env.objects:
    if obj.type.name in ["Texture2D", "Sprite"]:
            data = obj.read()
            dest = data.name + '.png'
            img = data.image 
            img.save(dest)
```

**Error**
```
Traceback (most recent call last):
  File "<stdin>", line 6, in <module>
  File "C:\Program Files\Python39\lib\site-packages\UnityPy\classes\Object.py", line 120, in __getattr__
    return getattr(self.type_tree, name)
AttributeError: 'NodeHelper' object has no attribute 'image'
```

**Bug**
Sprite is failing to produce image with specific file. Additionally, the error produced when this happens is not the most helpful for understanding why. I decided to take the exact same object and directly use it to call the `get_image_from_sprite` function and got this error instead:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python39\lib\site-packages\UnityPy\export\SpriteHelper.py", line 34, in get_image_from_sprite
    if m_Sprite.m_SpriteAtlas:
  File "C:\Program Files\Python39\lib\site-packages\UnityPy\classes\Object.py", line 120, in __getattr__
    return getattr(self.type_tree, name)
AttributeError: 'NodeHelper' object has no attribute 'm_SpriteAtlas'
```
So it looks if the sprite instance does not have that attribute for whatever reason, the function will completely fail to produce an image. 

**To Reproduce**
- Here is one such file where at least one of the sprites causes this issue: 
[testfile.zip](https://github.com/K0lb3/UnityPy/files/8656034/testfile.zip)

- following data:
  - Python version: 3.9.7
  - UnityPy version: 1.8.9

**Comment by K0lb3** [comment]
Thanks for reporting the issue.
It's fixed with version 1.8.12.
