### ISSUE TITLE
name 'reNot0' is not defined

### ISSUE THREAD

**Issue by AutumnSun1996** [K0lb3/UnityPy#112]
**Code**
A snippet of the code section that cases the bug or error.
```python
import UnityPy
env = UnityPy.load('f6047e303e4e3d0341007570a5948c05')
print('len:', len(env.objects))
```

**Error**
The error message that is produced by python.
```
Error loading, reverting to EndianBinaryReader:
 name 'reNot0' is not defined
len: 0
```

**Bug**
When loading some files, it prints  ` name 'reNot0' is not defined ` and returns no objects

**To Reproduce**
  - Python 3.8
  - UnityPy 1.8.13

Confirmed that same file is ok with UnityPy 1.7.24

I searched the code, and only usage for `reNot0` is just added by 5ecd94fb899b314f534ba1ee3a5975bd10a0364a

https://github.com/K0lb3/UnityPy/blob/5ecd94fb899b314f534ba1ee3a5975bd10a0364a/UnityPy/files/BundleFile.py#L138

seems u forgot to add the defination of it @K0lb3

**Comment by K0lb3** [comment]
Thanks again for reporting the issue and especially for the complete bug report.
I'm sorry for that dumb mistake.
