### ISSUE TITLE
Name 'reNot0' is not defined (Makes loaded file unusable in the program, as no files are loaded from it)

### ISSUE THREAD

**Issue by RandomUserrrr** [K0lb3/UnityPy#113]
**Code**
Example code from the readme

**Error**
No traceback, but got this error over and over every time it tried to open a file:
```
Error loading, reverting to EndianBinaryReader:
 name 'reNot0' is not defined
```

**Bug**
Looking at the code, it looks like the file BundleFile.py was just changed and a variable was used on line 138 that was not defined.

**To Reproduce**
- following data:
  - Python version 3.9.7
  - UnityPy version 1.8.13

**Comment by K0lb3** [comment]
Thanks for the report, and sorry for the inconvienience.
