### ISSUE TITLE
Python setup.py Fails from Source

### ISSUE THREAD

**Issue by russellvt** [K0lb3/UnityPy#115]
**Code**

After cloning the repository, it seems setuptools doesn't like `setup.py` ... also tested with 1.7.0 with same result.

`python3 setup.py install`

**Error**

Here's the overall output / error (note that I've reduced the preceding path to `~` to hide my directory layout, etc.)

```
~/UnityPy$ python setup.py install
Traceback (most recent call last):
  File "~/UnityPy/setup.py", line 2, in <module>
    from UnityPy import __version__ as version
  File "~/UnityPy/UnityPy/__init__.py", line 3, in <module>
    from .environment import Environment
  File "~/UnityPy/UnityPy/environment.py", line 6, in <module>
    from . import files
  File "~/UnityPy/UnityPy/files/__init__.py", line 1, in <module>
    from .File import File, DirectoryInfo
  File "~/UnityPy/UnityPy/files/File.py", line 2, in <module>
    from ..helpers import ImportHelper
  File "~/UnityPy/UnityPy/helpers/__init__.py", line 1, in <module>
    from . import CompressionHelper, ImportHelper, TypeTreeHelper
  File "~/UnityPy/UnityPy/helpers/CompressionHelper.py", line 5, in <module>
    import brotli
ModuleNotFoundError: No module named 'brotli'
```

**Bug**

This module *should*  install without issue. Note: Manually installing dependencies allow the module to make it to the compiler step..

```
pip install brotli
pip install lz4
pip install tabulate
pip install texture2ddecoder
pip install etcpak
pip install Pillow
```

**To Reproduce**
- `git clone https://github.com/K0lb3/UnityPy.git`
- `cd UnityPy`
-  `python3 -m venv venv`
- `. ./venv/bin/activate`
- `pip install pip --upgrade`
- `python3 setup.py install`

Version Information::
  - Python 3.9.10
  - UnityPy version: commit 32d4b91bf71cbbc1075e522b188d05a3f504f9d1 (Version doesn't matter)

**Comment by russellvt** [comment]
Verified this issue persists on various Python versions under `pyenv`...  `2.7.18`, `3.6.13`, `3.7.12` and `3.9.9` on an older Debian (O/S is OpenSSL 1.0, with OpenSSL 1.1 compiled and linked to Python 3.7 versions or more-recent).

**Comment by russellvt** [comment]
Looking at your Github Workflow... why are you pre-installing prerequisites to test a Python package? That assures there is *NO* test of the Python Setup, itself (ie: `python setup.py install` should *still* work, and GitHub should be allowed to test it via the workflow, etc).

**Comment by russellvt** [comment]
> Looking at your [Github Workflow](/UnityPy/blob/master/.github/workflows/python-package.yml) (Current Version - May Change in future updates)

Specific reference(s) in the .github/workflows/python-package.yml file ... Python install *should always use the defaults* to verify proper installation happens within the package, itself.

```
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel setuptools
        pip install --upgrade twine
        pip install -U lz4 brotli Pillow texture2ddecoder etcpak tabulate

    ...
```

**Comment by K0lb3** [comment]
You're right, the way it was setup was indeed a bit weird.
I can't even recall anymore why it was setup that way in the first place.
