### ISSUE TITLE
How to modify Sprite？

### ISSUE THREAD

**Issue by liang530** [K0lb3/UnityPy#121]
How to modify Sprite？

**Comment by K0lb3** [comment]
The currently only "well" supported option to do that is by editing the Texture2D that is used by the sprites.
To get the texture in question, you can replicate this section from [SpriteHelper](https://github.com/K0lb3/UnityPy/blob/826ed5dc5acfdfa5e1b005ee801dd29de03df153/UnityPy/export/SpriteHelper.py#L33).

**Comment by liang530** [comment]
Thank you. It has been solved
