### ISSUE TITLE
Question: How to get textual representation of MonoBehaviour type?

### ISSUE THREAD

**Issue by UserUnknownFactor** [K0lb3/UnityPy#13]
For example UABE can show the type like this: `0xFFFFFFFF (MonoBehaviour : UnityEngine.UI.Image (UnityEngine.UI.dll))`.
Is there a way to reproduce this with UnityPy? 
I don't really know specifics of the storage so I couldn't find where this information is...

**Comment by K0lb3** [comment]
I'm not sure how UABE links to the dlls and I never bothered with it, since most modern games use il2cpp.

Usually, MonoBehaviour objects contain a custom type tree that is used as a variable input for specific functions.
The use is quite diverse, e.g. as instruction set for how to assemble and transform multiple images for a UI, as a list for all game asset files, .....

**Comment by K0lb3** [comment]
![image](https://user-images.githubusercontent.com/29400616/90812864-0bd59d80-e327-11ea-92c7-d39c4c0a9752.png)

The reference to a function of a dll isn't necessary either and if it exists, it's saved as a string.

**Comment by UserUnknownFactor** [comment]
Can you please help with some generic code? 
I want to extract MonoBehaviours into separate folders by their corresponding function for example all `MonoBehaviour`s corresponding to `UnityEngine.UI.Image` function should go to `UnityEngine.UI.Image` folder.

The code for `AssetBatchConverter.py` I used to extract to the same folder already:
```python
  elif format == 'MonoBehaviour':
    extension = ".dat"
    with open(f"{fp}{extension}", "wb") as f: f.write(data.get_raw_data())
    return [obj.path_id]
```

**Comment by UserUnknownFactor** [comment]
Yay, found it. It turns out UABE shows `namespace` and `assembly_name` of the underlying `MonoScript` object there.  That got me confused. And the `MonoScript` always have them so they can be used like that. It's nice to know that `MonoBehaviour`s can contain `TypeName` though.

Here is the code for `AssetBatchConverter.py` I used to extract `MonoBehaviour`s into separate folders by their corresponding namespace:
```python
def export_obj(obj, fpath: str, asset: str) -> list:
  format = obj.type
  if format not in TYPES: return []

  data = obj.read()
  name = data.name if (data.name is not None and data.name != '') else "unnamed asset"
  fname, extension = os.path.splitext(name)

  name = "%s-%s-%d" % (fname, asset, obj.path_id)
  fp = os.path.join(fpath, name)
```

```python
  elif format == 'MonoBehaviour':
    extension = ".dat"
    script = data.script.read()
    if not script: return [obj.path_id]
    fp = os.path.join(fpath, script.namespace, name)
    os.makedirs(os.path.dirname(fp), exist_ok=True)
    with open(f"{fp}{extension}", "wb") as f: f.write(data.get_raw_data())
    return [obj.path_id]
```
