### ISSUE TITLE
NodeHelper breaks on dictionaries with non-string keys

### ISSUE THREAD

**Issue by rkevin-arch** [K0lb3/UnityPy#14]
I'm trying to load an `AssetBundleManifest` using UnityPy (apologies for the spaghetti code, just trying to get it working and see what's possible):
```python
import UnityPy
import requests
r = requests.get("<URL REDACTED, but literally any AssetBundleManifest would work>")
am = UnityPy.AssetsManager(r.content)
bundle = list(am.assets.values())[0]
abm = [i for i in bundle.objects.values() if i.class_id == UnityPy.enums.ClassIDType.AssetBundleManifest][0].read()
```
This all work, and I can see the resulting AssetBundleManifest:
![image](https://user-images.githubusercontent.com/5837628/91451714-8b390480-e832-11ea-807f-9e08e66769e8.png)

However, when I try to access an attribute like `abm.AssetBundleNames`, I just get a `NodeHelper` object and tab complete won't work:
![image](https://user-images.githubusercontent.com/5837628/91451811-a86dd300-e832-11ea-87fa-7cd905abaf34.png)

Using `dir` on it gives me an exception:
![image](https://user-images.githubusercontent.com/5837628/91451859-bcb1d000-e832-11ea-8df5-8f586bc1e36a.png)

I can still see all the asset bundle names if I do `abm.AssetBundleNames.__dict__`:
![image](https://user-images.githubusercontent.com/5837628/91452486-7ad55980-e833-11ea-8fa2-34e938a8171f.png)

I think the problem is `AssetBundleNames` is stored as a dict from `int` to `str`, and you're [just assigning everything in this dictionary to the object's `__dict__`](https://github.com/K0lb3/UnityPy/blob/9a4cfba95f8e524df3425eec81ede9555874803e/UnityPy/classes/Object.py#L93) when python expects every key in `__dict__` to be a string.

I'm not sure what the best way to fix this is, but maybe a type check for the keys and falling back to something else if the keys aren't strings might be a good idea. For now, I'm just operating directly on `abm.AssetBundleNames.__dict__`, which isn't ideal but works.

**Comment by K0lb3** [comment]
Thanks for the report.
I will include a fix for this with the next small update that will be released at the weekend.

**Comment by rkevin-arch** [comment]
Thanks! On a related note, in AssetBundleInfos there are AssetBundleHash objects that have attributes like `bytes[0]` to `bytes[15]`. Those aren't valid Python attribute names, so trying to access them directly won't work either:
![image](https://user-images.githubusercontent.com/5837628/91632123-893a8700-e993-11ea-987b-11388f9ec4a6.png)
So just checking if the dict has strings as keys won't work unless you also make sure the strings are valid python attribute names.

**Comment by K0lb3** [comment]
The update is out.

Atm the node helper simply converts the keys to strings because otherwise, it would break dir.

Can you upload the file which had these bytes so that I can figure out a way to solve that specific problem in a good way?


On another note,
it's easier to explore the mono behaviors and other "weird" object types via IDE debuggers.
