### ISSUE TITLE
PPtr Not Found

### ISSUE THREAD

**Issue by cruiseliu** [K0lb3/UnityPy#143]
Loading the attached file (from game My Time at Sandrock) yields "PPtr Not Found".
It can be normally loaded by AssetStudio.

**Code**
```python
print(UnityPy.load('trialdungeon_wreck').container)
```

**Error**
```
{'Assets/Scene/Additive/TrialDungeon_Wreck.unity': <PPtr Not Found>}
```

**To Reproduce**
- a copy of the file that causes the problem: [trialdungeon_wreck.zip](https://github.com/K0lb3/UnityPy/files/9796888/trialdungeon_wreck.zip)

- following data:
  - Python version: 3.10.8
  - UnityPy version: 1.9.15

**Comment by K0lb3** [comment]
AssetStudio can't resolve it either
![Screenshot 2022-10-19 003648](https://user-images.githubusercontent.com/29400616/196558160-fb019884-f197-4cb2-b6b3-a24d6f72eaf8.png)

Just use Unity.load(fp).objects instead of the container.
The pointer that is used for the container is invalid, it points to an object with the path id of 0, which just doesn't exist.

**Comment by cruiseliu** [comment]
Thanks for your help!
How to get those "name"s in AssetStudio?
'''
>>> bundle = UnityPy.load('trialdungeon_wreck')
>>> obj = bundle.objects[-3].read()
>>> obj.path_id
35
>>> obj.name
''
'''

**Comment by cruiseliu** [comment]
And I found two litter problems.
1. `UnityPy.load()` does not accept `pathlib.Path`.
2. `Transform.__str__()` raises exception.
```
>>> str(bundle.objects[36].read())
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/home/lz/.local/lib/python3.10/site-packages/UnityPy/classes/Object.py", line 116, in __repr__
return "<%s %s>" % (self.__class__.__name__, self.name)
File "/home/lz/.local/lib/python3.10/site-packages/UnityPy/classes/Object.py", line 110, in __getattr__
return getattr(self.type_tree, name)
AttributeError: 'NodeHelper' object has no attribute 'name'
```

**Comment by cruiseliu** [comment]
> obj.read().name, but mind that not all object types carry names.

The code snippet I pasted above refers to "LightProbeFixer" in the screenshot (the 3rd last line).
`object.read().name` returns empty string while AssetStudio gives a name.

 I have two more questions.

Would you consider add fields like `type` and `path_id` to `NodeHelper`? It took me a while to realize its a wrapped object.

And sorry for being off topic, when an object references an external file, saying `Couldn't find dependency CAB-522b...`, is there a way to find which is the referred file? Maybe through someting like `asset.cab_uuid`? I don't want to load all asset bundles in the game.

**Comment by cruiseliu** [comment]
Oh I found it.
AssetStudio uses `MonoBehaviour.Script.Name` if `MonoBehaviour.Name` is empty.
Seems this logic should be left to library user.
