### ISSUE TITLE
Python interpreter crash (segmentation fault)

### ISSUE THREAD

**Issue by cruiseliu** [K0lb3/UnityPy#148]
**Code & Error**
```
>>> import UnityPy
>>> UnityPy.load('config').objects[1084].read()
Segmentation fault (core dumped)
```

**To Reproduce**
- a copy of the file that causes the problem: [config.zip](https://github.com/K0lb3/UnityPy/files/9892647/config.zip)

- following data:
  - Python version: 3.10.8
  - UnityPy version: 1.9.19

**Comment by K0lb3** [comment]
Thanks for reporting the issue and including the file.
The fix for it will be out in a bit.
