### ISSUE TITLE
Can't get object's container in some case.

### ISSUE THREAD

**Issue by timelic** [K0lb3/UnityPy#150]
**Code**
A snippet of the code section that cases the bug or error.
```
import UnityPy
def test():
    env = UnityPy.load("./data.unity3d")
    for obj in env.objects:
        if obj.type.name in ["TextAsset"]:
            data = obj.read()
            print(obj.container, data.name, obj.path_id)
if __name__ == "__main__":
    test()


>>> None IDS_STRUCTURE_SELECT 2025
>>> None IDS_EVENT_NOTIFY 2026
```

**Error**
No error.

**Bug**
When I use the above code to try other Unity resource files, it can output the correct `obj.container`, but when I try the `data.unity3d` file, its output `obj.container` is `None`.
I use Asset Studio to open the same `data.unity3d` file, and I can get the correct `container`.
![image](https://user-images.githubusercontent.com/20257354/199890683-413b8612-6e21-4a45-8e9d-4978834a0254.png)

**To Reproduce**
- a copy of the file that causes the problem
  - https://drive.google.com/file/d/1MV77-wdyiwXjErEIwSFcqs6eKG1Sh39F/view?usp=sharing
- following data:
  - Python version 3.9.13
  - UnityPy version 1.9.20

**Comment by K0lb3** [comment]
There is an additional way that container paths can be designated beside the already implemented option.
I wasn't aware of this point until now, so thanks for opening the issue.

The container paths, in this case, have to be fetched from an object of the ResourceManager type,
which assigns the container paths for all objects within the BundleFile.
Implementing this in UnityPy would be a bit more work so I won't implement it any time soon.
Maybe with the next major version, I hope to release around new year.

For now, you can use the following snippet to get the container path:
```python
env = UnityPy.load("data.unity3d")
for obj in env.objects:
    if obj.type.name == 'ResourceManager':
        rm = obj.read()
        for key, ptr in rm.m_Container.items():
            print(key, ptr)
            data = ptr.read()
    break
```

**Comment by timelic** [comment]
Thanks for your detailed reply, which is very helpful for my project🫡
