### ISSUE TITLE
PPtr objects never return true when getting bool value

### ISSUE THREAD

**Issue by StarHeartHunt** [K0lb3/UnityPy#16]
In UnityPy/export/SpriteHelper.py [L24](https://github.com/K0lb3/UnityPy/blob/4733a5d184c03d876782f35a0332897df46456cb/UnityPy/export/SpriteHelper.py#L24) , the alpha_texture will always be __False__ due to the `__bool__` method in UnityPy/classes/PPtr.py [L56](https://github.com/K0lb3/UnityPy/blob/4733a5d184c03d876782f35a0332897df46456cb/UnityPy/classes/PPtr.py#L56).
That means alpha channel will never be automatically merged into original image, but it seems to be unexpected.
Also Unitypack has the same problem, Is it a mistake when copied from Unitypack?

**Comment by K0lb3** [comment]
Good catch.
Looks like I accidently made a bad edit some time down the line.
I will fix it during the next few days.


ps: unitypack doesn't even have a function on its own to extract sprites :P

**Comment by K0lb3** [comment]
I remembered why there is still that __bool__ function.
The PPtrs used to be resolved the moment they were created.
PPtrs that couldn't be resolved stayed PPtrs, those that did became actual pointers towards the target.
The current __bool__ function stems from that time.

**Comment by K0lb3** [comment]
A fix will be published in some hours.

**Comment by K0lb3** [comment]
Fixed in [1.5](https://github.com/K0lb3/UnityPy/commit/89de7f42e451bb84cd72214e22b3dc20075ecb4a)
