### ISSUE TITLE
Reading MonoBehaviors through the type tree is normal, but it becomes abnormal after saving.

### ISSUE THREAD

**Issue by yeooii** [K0lb3/UnityPy#181]
![a](https://user-images.githubusercontent.com/96559248/233256834-3d10ff45-28f5-4eb1-88b9-7e389e7ed396.png)
![b](https://user-images.githubusercontent.com/96559248/233256843-7cc3edd5-bfc3-4815-ba88-38a67e377f02.png)

**Comment by yeooii** [comment]
I am using obj.read_ When typetree() is used, all content is normal. But I use obj.save_ After typetree() is saved, it becomes the image shown above.

**Comment by yeooii** [comment]
The image on the left is before modification, while the image on the right is modified using the type tree

**Comment by K0lb3** [comment]
The issue is likely related to https://github.com/K0lb3/TypeTreeGenerator/pull/2 in case you used generated typetrees.
If not, can you provide a sample asset?

**Comment by AhmedAhmedEG** [comment]
Please provide sample code, did you given the nodes as input to .save_typetree() function?

**Comment by AhmedAhmedEG** [comment]
> The issue is likely related to [K0lb3/TypeTreeGenerator#2](https://github.com/K0lb3/TypeTreeGenerator/pull/2) in case you used generated typetrees. If not, can you provide a sample asset?

His problem is that after saving an object, some values changes, that merge request you mentioned removed extra indentations that was being added to type tree json files created by TypeTreeGenerator, so It's totally different from his problem.
