### ISSUE TITLE
export sprite error: unpack requires a buffer of 8 bytes

### ISSUE THREAD

**Issue by liang530** [K0lb3/UnityPy#182]
**Code**
UnityPy/classes/Sprite.py     def __init__(self, reader)  function bug:
![AE7C16D4-9B6A-4810-802D-C7FB12C11EFF](https://user-images.githubusercontent.com/7912074/234156077-fd44f79e-fe41-4dbd-aa1b-326553de3330.png)

1. The SpriteBone() function is missing a parameter
2. self.m_ Bones=[reader. read_vector2array() for _ in range (mBonesSize)] Some images may be error

**Error**
export sprite is error:
<img width="1018" alt="QQ20230425-100244@2x" src="https://user-images.githubusercontent.com/7912074/234156297-a7f35385-7714-4976-8a0c-3066892c9475.png">

**Bug**
- AssetStudioGui export is ok！
- The example of reproducing this bug is in Data.zip,and sharedassets15.assets/path_id=6, where you can directly execute "test_export_error.py" can be reproduced
- I hope to fix this bug. Thank you very much

**To Reproduce**
- [Data.zip](https://github.com/K0lb3/UnityPy/files/11315786/Data.zip)
- following data:
  - Python 3.8
  - UnityPy 1.9.28

**Comment by K0lb3** [comment]
Thanks for reporting the issue,
I will try to take a look in due time.
