### ISSUE TITLE
TextureFormat.ASTC_RGB_8x8 quality is slightly reduced.

### ISSUE THREAD

**Issue by Thura122016** [K0lb3/UnityPy#188]
**Bug**
When I edit TextureFormat.ASTC_RGB_8x8, It changes the TextureFormat.ETC2_RGBA8 and the image quality is slightly reduced.
Can you fix it or How can I?

**Comment by K0lb3** [comment]
All texture compression algorithms employed by Unity are lossy.
When replacing a texture, it either has to be stored as uncompressed type or has to be compressed again.
Uncompressed increases the size of the asset by a lot (2~8x of the original image data size), while recompression creates a loss in quality.

You can set an uncompressed target texture type by using [Texture2D.set_image](https://github.com/K0lb3/UnityPy/blob/8c8492fbdb713b45517a337ab98a0c9793787b2d/UnityPy/classes/Texture2D.py#L81). You can achieve no compression by using TextureFormat.RGBA32.
