### ISSUE TITLE
Crashes when reading RGB24 Texture2D

### ISSUE THREAD

**Issue by JunkBeat** [K0lb3/UnityPy#211]
Here's my code. No error is given, the script just crashes:
```
def readTexture2D(obj: Texture2D):
    try:
        data = obj.read()
        img = data.image
    except Exception as e:
        print(f"[Error] Unable to load image: {e}")
        return
```

For now I'm using a stub to avoid problems:
```
tree = obj.read_typetree()
if tree["m_TextureFormat"] == 3:
    raise Exception("[Error] Unsupported format (RGB24)")  
```      

Assets: https://drive.google.com/file/d/1hbofMD1ZEZZGCN6V8bntgrhpumdAumQh/view?usp=sharing
Python version: 3.10.2
UnityPy version: 1.10.3

**Comment by K0lb3** [comment]
I can't replicate this.
My test script finishes without any issue showing up.

```python
import UnityPy

env = UnityPy.load("resources.assets")
for obj in env.objects:
    if obj.type.name == "Texture2D":
        print(x, x.m_TextureFormat)
        x = obj.read()
        x2 = obj.read_typetree()
        x.image
        
print("done")
`````

**Comment by K0lb3** [comment]
Furthermore....the data is being passed to PIL,
so the issue is most likely not related to UnityPy, as it uses no unsafe code itself.
