### ISSUE TITLE
wishlist: support "bundle"/"bank"?

### ISSUE THREAD

**Issue by hydrargyrum** [K0lb3/UnityPy#215]
In "life of delta" game, there are standard `level*` files and `sharedassets*.assets` files that contain a lot of resources of the game. However, it seems they don't contain everything, some music can't be found inside them. But the game has a `StreamingAssets` subfolder that contains those files:

```
(name_conflict)_music.bank
(name_conflict)_sfx.bank
Master Bank.bank
Master Bank.strings.bank
Master Bank_dst.bank
music.bank
sfx.bank
StreamingAssets
StreamingAssets.manifest
ui.bank
```

Only StreamingAssets seems to be recognized by unitypy, and contains:

```
<ClassIDType.AssetBundle: 142>
<ClassIDType.AssetBundleManifest: 290>
```

Not sure what to do from there.

**Comment by K0lb3** [comment]
This is not a bug, and not a parsing problem.
As a simple Google check would have told you.... .bank files are music files, usually played via FMOD by Unity, and not Unity asset files.
