### ISSUE TITLE
AudioClip can not be exported. What does the FmodError : MEMORY mean??

### ISSUE THREAD

**Issue by sai4311b** [K0lb3/UnityPy#220]
**Code**

import UnityPy
file_path = '/content/se-mp3.bin'
env = UnityPy.load(file_path)
data = env.objects[1].read()
extractor.exportAudioClip(data,'test.wav')

**Error**
![example](https://github.com/K0lb3/UnityPy/assets/154989876/8ee23944-9979-443a-8d41-8ee9a44f8164)

**Bug**
A description of what you expect to happen/see and what actually happens.

Please help me solve the problem.
I wnat to export the audioclip from the sample asset file below but it shows FmodError: MEMORY and I have no idea to solve it.

**To Reproduce**
- a copy of the file that causes the problem
https://drive.google.com/file/d/13hYHiqDIICtbbBETPTxz7jMRgyMSjTiN/view?usp=drive_link

- following data:
  - Python version
  Python 3.10.12 on Google colab 
  - UnityPy version
  1.10.7 (latest)

**Comment by K0lb3** [comment]
To be specific, it's actually a problem of fmod itself.
It doesn't seem to ship a m4a decoder in it's studio library for normal computer use.

**Comment by isHarryh** [comment]
I also encountered this error. `pyfmodex.exceptions.FmodError` But my cause is an other one.

#### Cause
When using **multithreading** to get `anyAudioClip.samples` property (equivalent to invoke `AudioClipConverter.extract_audioclip_samples`), this error may occurred. So, it may be a concurrent issue that `pyfmodex` has.

#### My Solution
Use `threading.Lock` to protect the code where you call these methods.
