### ISSUE TITLE
error when exporting mesh_renderer

### ISSUE THREAD

**Issue by bcatbat** [K0lb3/UnityPy#228]
here is my code:
```python
if mr.m_GameObject:
    gameobject = mr.m_GameObject.read()
    export_dir = os.path.join(dst_folder, gameobject.name)
    mr.export(export_dir)
```
just follow your doc example.
it raises an exception `local variable 'mesh' referenced before assignment` at line `mr.export(export_dir)`.

here is your code:
```python
# MeshRendererExporter.py
def export_mesh_renderer(obj: Renderer, export_dir: str) -> None:
    env = mesh.assets_file.enviroment
    env.fs.makedirs(export_dir, exist_ok=True)
```

i think it should be:
```python
    env = obj.assets_file.environment
    env.fs.makedirs(export_dir, exist_ok=True)
```
`mesh` is a field name mistake. and `enviroment` should be `environment`

**Comment by K0lb3** [comment]
You're right.....and I totally forgot about your opened issue for nearly a whole year.....
Going to fix it now, thanks for reporting it.
