### ISSUE TITLE
The container attribute of the file cannot be read correctly

### ISSUE THREAD

**Issue by nijinekoyo** [K0lb3/UnityPy#236]
**Code**
``` python
objectType = object.type.name
objectContainer = object.container
if objectType not in exportTypes:
    return

try:
    fileData = object.read()
except Exception as e:
    print(f"Error: {e}")
    return

if hasattr(fileData, "name") == False or fileData.name is None or fileData.name == "":
    return

fileName = fileData.name

if objectType == 'Mesh':
    print(object.container) # print None
```

**Bug**
The same file can get container information in AssetStudio, but it cannot be obtained normally with UnityPy. Print will get `None`
<img width="634" alt="image" src="https://github.com/K0lb3/UnityPy/assets/125987288/c186891d-6c5c-4656-88b4-c80e7dbb5b62">

**To Reproduce**
- a copy of the file that causes the problem
File: [mdl_chr_fktn-casl-0000_body.zip](https://github.com/K0lb3/UnityPy/files/15448199/mdl_chr_fktn-casl-0000_body.zip)
Unity Version: 2022.3.21f1
- following data:
  - Python version: 3.10.11
  - UnityPy version: 1.10.13

**Comment by K0lb3** [comment]
AssetStudio uses the container path of a prefab on all items used by a prefab that don't have a container path on their own.
UnityPy doesn't employ this strategy, as doing this requires parsing the whole node tree.
