### ISSUE TITLE
`reader` not defined bug and unterminated string

### ISSUE THREAD

**Issue by RayFirefist** [K0lb3/UnityPy#25]
On `SerializedFile.py` under `read_serialized_type` function, I got an exception saying `reader` is not defined.
After fixing that (by changing it in `self.reader`) actually, I found out that there's more. I found out that there's also an issue with the reading of the type `Unterminated string: [b'']`.

I'm also providing the sample file for it (it's decrypted, so there shouldn't be any encryption/xor/anything else issue).

Unity version: 2019.4.1f1

[bundle.zip](https://github.com/K0lb3/UnityPy/files/5445012/bundle.zip)

**Comment by K0lb3** [comment]
A fix will be published in some hours.

**Comment by K0lb3** [comment]
fixed in [1.5](https://github.com/K0lb3/UnityPy/commit/89de7f42e451bb84cd72214e22b3dc20075ecb4a)

The problem was located in the type tree loading.
