### ISSUE TITLE
Suggestion: object generator and more extensive loading/saving options

### ISSUE THREAD

**Issue by UserUnknownFactor** [K0lb3/UnityPy#26]
I think it would be better if you could re-implement #22 in a way you think would be more appropriate for the project.

What I basically thought is missing:
- Example of dumping / restoring raw `MonoBehaviour`s.
- Example of iterating over objects without writing additional code for getting `local asset path`, `asset file name` etc each time.
- Some kind of generator or iterator over objects in all files with progress function changing option that provides the aforementioned things.
- Function (ex. `am.save("lz4")`) for auto-saving all changed files using the generator in the `Environment` class. It could be overridden if some project needs more but in most cases it should be enough by itself.

**Comment by K0lb3** [comment]
I'm sorry that I didn't reply earlier,
my laptop died and it took some time until I got a replacement.

I will look into it at the weekend.
