### ISSUE TITLE
Missing information on urp shader m_Passes

### ISSUE THREAD

**Issue by Peter6666** [K0lb3/UnityPy#266]
Missing information on urp shader m_Passes
For example, m_Passes has 10 arrays but only displays 3

**Comment by Peter6666** [comment]
For example, m_Passes has 10 arrays but only displays 3

**Comment by K0lb3** [comment]
First of all, this information alone without sample doesn't tell me anything,
besides that it could be a version related issue - about anywhere - aka - not fix-able or even investigatable.

#264 should solve it, IF the issue is related to the shader parsing.
