### ISSUE TITLE
TypeError: MonoScript.__init__() missing 1 required keyword-only argument: 'm_Script'

### ISSUE THREAD

**Issue by mos9527** [K0lb3/UnityPy#271]
**Code**
```python
import UnityPy
import UnityPy.config

UnityPy.config.FALLBACK_UNITY_VERSION = "2022.3.21f1"
UnityPy.config.FALLBACK_VERSION_WARNED = True
path = r"0001"

from UnityPy.helpers import TypeTreeHelper
TypeTreeHelper.read_typetree_boost = False

env = UnityPy.load(path)
for obj in env.objects:
    r = obj.read()
```

**Error**
```powershell
Traceback (most recent call last):
  File "C:\Users\mos9527\UnityPy\UnityPy\helpers\TypeTreeHelper.py", line 179, in read_value
    value = clz(**clz_kwargs)
            ^^^^^^^^^^^^^^^^^
TypeError: MonoScript.__init__() missing 1 required keyword-only argument: 'm_Script'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mos9527\UnityPy\local_test.py", line 14, in <module>
    r = obj.read()
        ^^^^^^^^^^
  File "C:\Users\mos9527\UnityPy\UnityPy\files\ObjectReader.py", line 174, in read
    obj = self.read_typetree(wrap=True)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mos9527\UnityPy\UnityPy\files\ObjectReader.py", line 209, in read_typetree
    ret = TypeTreeHelper.read_typetree(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mos9527\UnityPy\UnityPy\helpers\TypeTreeHelper.py", line 101, in read_typetree
    obj = read_value(root_node, reader, as_dict, assetsfile)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mos9527\UnityPy\UnityPy\helpers\TypeTreeHelper.py", line 182, in read_value
    value = clz(
            ^^^^
TypeError: MonoScript.__init__() missing 1 required keyword-only argument: 'm_Script'
```

**Bug**
`MonoScript` objects can't be read properly as the new TypeTree reader wants to read its `m_Script` field, which doesn't seem to be present in [pre-1.20 UnityPy](https://github.com/K0lb3/UnityPy/blob/47b1bde027fd79d78af3de4d5e3bebd05f8ceeb8/UnityPy/classes/MonoScript.py#L4). 
Modifiying the generated definition for `TextAsset` seems to allow this object to be read. 
```python
@define(kw_only=True, slots=False)
class TextAsset(NamedObject):
  m_Name: str
  m_Script: Optional[str] = None # <-- Changed from `m_Script: str`
  m_PathName: Optional[str] = None
  ...
@define(kw_only=True, slots=False)
class MonoScript(TextAsset):
  m_AssemblyName: str
  m_ClassName: str
  m_ExecutionOrder: int
  m_Name: str
  m_Namespace: str
  m_PropertiesHash: Union[Hash128, int]
  m_IsEditorScript: Optional[bool] = None
```
This issue can be reproduced with both the Python and C implementation of `read_typetree`

**To Reproduce**
- a copy of the file that causes the problem
[0001.zip](https://github.com/user-attachments/files/17179224/0001.zip)
Its Unity version is stripped (which should be `2022.3.21f1`)
- following data:
  - Python version: 3.12.6
  - UnityPy version: 1.20.2

**Addendum**
The section of the README [on disabling the C typetree reader](https://github.com/K0lb3/UnityPy/tree/master?tab=readme-ov-file#crash-without-warningerror) is out of date. `read_typetree_boost` should be modified instead of `read_typetree_c` in the current UnityPy version.

**Comment by K0lb3** [comment]
1.20.3 fixes the issue.

I never really noticed that MonoScript inherits from TextAsset for some reason.
I hacked the attrs.define function usage a bit, so it now ignores the base classes of the given classes,
and only checks the fields of the given class.

While this basically violates the usual inheritance scheme,
it's probably better that way, as most cases where one wants the check against a class, e.g. for renderers, it works out fine.

**Comment by mos9527** [comment]
Tested with 1.20.3 and this is indeed fixed. Thanks!
