### ISSUE TITLE
The issue of Textures2D not being able to use the ASTC_RGB_6x6 format.

### ISSUE THREAD

**Issue by 1103945342** [K0lb3/UnityPy#274]
Dear Author：

                     Hello! I encountered a small issue while using your library. When processing Textures2D, I am unable to set the Textures2D compression mode to ASTC_RGB_6x6. After setting it, it automatically changes to ETC2_RGBA8. I have tried other formats, and most of them also automatically change to ETC2_RGBA8. I would like to know what might be causing this issue. Below is my code snippet.

# 获取支持的图像格式
supported_formats = [
    'Alpha8', 'ARGB4444', 'RGB24', 'RGBA32', 'ARGB32', 'ARGBFloat', 'RGB565', 'BGR24', 'R16', 
    'DXT1', 'DXT3', 'DXT5', 'RGBA4444', 'BGRA32', 'RHalf', 'RGHalf', 'RGBAHalf', 'RFloat', 
    'RGFloat', 'RGBAFloat', 'YUY2', 'RGB9e5Float', 'RGBFloat', 'BC6H', 'BC7', 'BC4', 'BC5', 
    'DXT1Crunched', 'DXT5Crunched', 'PVRTC_RGB2', 'PVRTC_RGBA2', 'PVRTC_RGB4', 'PVRTC_RGBA4', 
    'ETC_RGB4', 'ATC_RGB4', 'ATC_RGBA8', 'EAC_R', 'EAC_R_SIGNED', 'EAC_RG', 'EAC_RG_SIGNED', 
    'ETC2_RGB', 'ETC2_RGBA1', 'ETC2_RGBA8', 'ASTC_RGB_4x4', 'ASTC_RGB_5x5', 'ASTC_RGB_6x6', 
    'ASTC_RGB_8x8', 'ASTC_RGB_10x10', 'ASTC_RGB_12x12', 'ASTC_RGBA_4x4', 'ASTC_RGBA_5x5', 
    'ASTC_RGBA_6x6', 'ASTC_RGBA_8x8', 'ASTC_RGBA_10x10', 'ASTC_RGBA_12x12', 'ETC_RGB4_3DS', 
    'ETC_RGBA8_3DS', 'RG16', 'R8', 'ETC_RGB4Crunched', 'ETC2_RGBA8Crunched', 'ASTC_HDR_4x4', 
    'ASTC_HDR_5x5', 'ASTC_HDR_6x6', 'ASTC_HDR_8x8', 'ASTC_HDR_10x10', 'ASTC_HDR_12x12', 
    'RG32', 'RGB48', 'RGBA64', 'R8_SIGNED', 'RG16_SIGNED', 'RGB24_SIGNED', 
    'RGBA32_SIGNED', 'R16_SIGNED', 'RG32_SIGNED', 'RGB48_SIGNED', 'RGBA64_SIGNED'
]

def convert_format(format_name):
    # 根据字符串格式名转换为 TextureFormat 枚举
    try:
        return TextureFormat[format_name]
    except KeyError:
        print(f"Unsupported format: {format_name}")
        return None

def process_images(src, selected_textures, new_images_folder, selected_format):
    env = UnityPy.load(src)

    for obj in env.objects:
        if obj.type.name == "Texture2D":
            data = obj.read()
            if data.m_Name in selected_textures:
                print(f"Replacing texture: {data.m_Name}")

                # 生成新的图像路径
                new_image_path = os.path.join(new_images_folder, f"{data.m_Name}.png")

                # 检查新图像是否存在
                if os.path.isfile(new_image_path):
                    new_image = Image.open(new_image_path)

                    # 更新纹理数据
                    data.image = new_image

                    # 获取图像的字节大小并更新 m_CompleteImageSize
                    img_byte_arr = io.BytesIO()
                    new_image.save(img_byte_arr, format='PNG')  # 保存为 PNG 格式
                    img_size = img_byte_arr.tell()
                    data.m_CompleteImageSize = img_size  # 更新 m_CompleteImageSize

                    # 打印字节大小
                    print(f"图像 '{data.m_Name}' 的字节大小: {img_size} 字节")

                    # 使用用户选择的压缩格式
                    tex_format = convert_format(selected_format)
                    if tex_format:
                        print(f"使用的压缩格式: {tex_format.name}")
                        data.set_image(new_image, target_format=tex_format)

I look forward to your reply.THANTKS！

**Comment by K0lb3** [comment]
UnityPy currently doesn't have inbuild support for ASTC compression.
So, if you want to switch the texture format of Texture2D to ASTC, you have to do the following.

1. install [astc-encoder-py](https://github.com/K0lb3/astc-encoder-py)
2. correctly patch the Texture2D by hand
```py
from PIL import Image

from astc_encoder import (
 ASTCConfig,
 ASTCContext,
 ASTCImage,
 ASTCProfile,
 ASTCSwizzle,
 ASTCType,
)
from UnityPy.enums import TextureFormat

def set_astc_6x6_data(texture: Texture2D, img_fp: str):
  config = ASTCConfig(ASTCProfile.LDR_SRGB, 6, 6)
  context = ASTCContext(config)
  img = Image.open(img_fp).convert("RGBA")
  image = ASTCImage(ASTCType.U8, *img.size, data=img.tobytes())
  swizzle = ASTCSwizzle.from_str("RGBA")
  comp = context.compress(image, swizzle)
  
  texture.image_data = comp
  texture.m_CompleteImageSize  = len(comp)
  texture.m_TextureFormat = TextureFormat.ASTC_RGB_6x6
  texture.save()
  ```

You might also have to turn off mipmaps using this code directly.



Regarding the other points,

Considering that you say the texture format stays ``ETC2_RGBA8, `` it means that your ``convert_format`` function returns a false value.
Otherwise, ``data.set_image`` would default to ``RGBA_32`` as it would default to this if it doesn't find a compression implementation for the given format, which is the case for ``ASTC_6x6``.

After setting the image, ``data.save()`` would also have to be called.

**Comment by 1103945342** [comment]
Wow, thank you so much. My problem has been perfectly resolved and I have now correctly set my target format to ASTC_RGBA_6x6！
