### ISSUE TITLE
`extractor.py` needs to be updated

### ISSUE THREAD

**Issue by Nattsu39** [K0lb3/UnityPy#284]
**Code**
I simply used the export function from [extractor.py](https://github.com/K0lb3/UnityPy/blob/master/UnityPy/tools/extractor.py)

**Error**
The error message that is produced by python.
```
File ".venv\lib\site-packages\UnityPy\tools\extractor.py", line 251, in exportSprite
    (obj.assets_file, obj.path_id)
AttributeError: 'Sprite' object has no attribute 'path_id'
```
**Bug**
export function is incompatible with the new version of Object subclass implementation.
Added: Sprite objects can be saved correctly before the exception occurs, but other objects cannot.

**To Reproduce**
- [bundle.zip](https://github.com/user-attachments/files/17713015/bundle.zip)

- following data:
  - Python version 3.10.11
  - UnityPy version 1.20.12

**Comment by K0lb3** [comment]
Thanks for the report.
I completely forgot about the extractor, it's one of the parts of UnityPy that have to be completely rewritten some time.

I updated it just now, applied some other minor fixes, and added a test for it, so it should work from now one.
