### ISSUE TITLE
Bundle folder structure

### ISSUE THREAD

**Issue by Dimbreath** [K0lb3/UnityPy#3]
Some bundle files contain folder structures in them, would be nice if it was possible to see under which folder the files are stored on. Unity Studio does it but it does break sometimes and only display asset name.

**Comment by K0lb3** [comment]
This is already implemented.
The path isn't stored in the bundle - it's stored in the assets of the bundle and it isn't always given.
Some objects may have actual paths, but most don't.
These paths are stored in AssetBundle objects.

UnityPy generates a dict called "container" (asset.container) for each asset if it finds an AssetBundle object in the asset.
This dict connects the given name (key) with the object (value).

The [extractor example](https://github.com/K0lb3/UnityPy/blob/master/AssetBatchConverter.py) actually uses this.

All objects which have an actual path also have a "container" key which contains the path.

![image](https://user-images.githubusercontent.com/29400616/72798731-f8087280-3c43-11ea-96d2-2ad2623840b2.png)

**Comment by Dimbreath** [comment]
Interesting. I seem to have missed that example. Sorry and thanks!
