### ISSUE TITLE
EndianBinaryWriter.write_aligned_string(value)

### ISSUE THREAD

**Issue by ChenLauter** [K0lb3/UnityPy#34]
When I input Chinese characters,len(value) is not the correct length of this string.
Should we use str.encode()?

**Comment by K0lb3** [comment]
You're right,
the length of the encoded string should be used and not the length of the string.

I pushed a fix with [1.6.5.5](https://github.com/K0lb3/UnityPy/commit/c94da5e8aa1e98d07ffe576715dea8b95c5ce062) just now.

**Comment by ChenLauter** [comment]
done
