### ISSUE TITLE
error happened when use the simple example code.

### ISSUE THREAD

**Issue by youZhuang** [K0lb3/UnityPy#37]
**Code**
A snippet of the code section that cases the bug or error.

                if obj.type in ["Texture2D", "Sprite"]:
                    # parse the object data
                    data = obj.read()

                    # create destination path
                    dest = os.path.join(destination_folder, data.name)

                    # make sure that the extension is correct
                    # you probably only want to do so with images/textures
                    dest, ext = os.path.splitext(dest)
                    dest = dest + ".png"

                    img = data.image
                    img.save(dest)
**Error**
The error message that is produced by python.

Traceback (most recent call last):
  File "/Users/zhuangyou/opt/anaconda3/lib/python3.7/site-packages/PIL/ImageFile.py", line 496, in _save
    fh = fp.fileno()
AttributeError: '_idat' object has no attribute 'fileno'

**Bug**
A description of what you expect to happen/see and what actually happens.

**To Reproduce**
- a copy of the file that causes the problem
- following data:
  - Python version 3.7
  - UnityPy version 1.6.7

**Comment by K0lb3** [comment]
Texture2Ds can be empty, so Sprites that use them will cause this error.
This can happen for various reasons, but it's usually quite rare overall.

I haven't come around to make a custom exception for errors such as that yet,
but one way or another problems such as that have to be handled via an if check or a simply try/except.

**Comment by youZhuang** [comment]
OK,Thanks.
