### ISSUE TITLE
Can't decompress font with 'KerningValues_size' > 0

### ISSUE THREAD

**Issue by jesliwang** [K0lb3/UnityPy#40]
**Code**
Font.py:24
for i in range(KerningValues_size):
                reader.Position += 8

**Error**
FontData_size -1082130432 FLARESERIF-821-BT 
FontData_size 85688 SukhumvitSet-Text 
FontData_size -1082130432 FLARESERIF-821-BOLD-BT 
FontData_size -1082130432 Arial

get wrong FontData_size 

**Bug**
I TEST AND TRY. When it changes  to 'reader.Position += 8' To 'reader.read_int() reader.read_int() ', EVERYTHING WILL BE OK!!!!

**To Reproduce**
1. Get "State of Survival Survive the Zombie Apocalypse_v1.10.10_apkpure.com" from internet

**Comment by K0lb3** [comment]
Thanks for the report.

The position handling still has some issues atm and I will try to fix the underlying problem to solve this kind of problem for good.

**Comment by K0lb3** [comment]
[1.6.7.2 - ObjectReader.Position fix](https://github.com/K0lb3/UnityPy/commit/390025aae56a4105f2001525d0ab0d1e0555eaab) should have fixed the issue.
I also streamlined the Font class a bit so that it uses the original C# naming style and added the general export code to the readme.

**Comment by jesliwang** [comment]
Sorry for my late reply!! It works well, GREAT WORK!!!
