### ISSUE TITLE
MonoBehaviour Raw-data Import

### ISSUE THREAD

**Issue by Nuked88** [K0lb3/UnityPy#43]
So,
I'm trying to export raw-data from MonoBehaviour, edit it and then reimport it

The export part was pretty easy, I've managed to export only the raw part that I need, but, for the import, part I don't know how to do it.
I've tried to follow the patch example but I've encountered some issue and at the end it doesn't work..

This is my code:

`   

    file_name = "resources.assets"
    file_path = os.path.join(root, "asset/resources.assets")
    e = UnityPy.load(file_path)
    
    for obj in e.objects:
 
        if obj.type == "MonoBehaviour":
  
            data = obj.read()               
            namer=data.name

            if data.name=="GeneralLockitEnglish":

                with open(os.path.join(destination_folder, f"{file_name}-{namer}.txt"), "rb") as fr:
                    data.raw_data=fr.read()

    with open(os.path.join(root, "file_patched"), "wb") as f:
        f.write(e.file.save()) 
    
    

I've added a setter to the MonoBehaviour like this:
`     @raw_data.setter`   

    def raw_data(self, val):

        self._raw_offset = val

The result is that the same file is saved without any changes
Probably the problem could be the setter since I'not so good with python, but I don't have found any example about restoring edited raw-data  on MonoBehaviour

Please I kinda lost here 🤣

**Comment by K0lb3** [comment]
First of all,
editing the raw data of MonoBehaviours usually doesn't work,
as it's parsed by a specific typetree with specific types.

So entries require an alignment of the stream/data,
others like strings, arrays, maps, and binary data also require an adjustment of the length before the data itself.


I'm working on a reworked typetree reader at the moment that can handle generated typetrees for MonoBehaviours and also makes it possible to save the edited data via the typetree structure.
It's more or less done and only needs some follow-up stuff like documentation, adjustment of existing code, and a test for it.

**Comment by Nuked88** [comment]
Ok perfect, just for info, the alignment should occur even if I don't change the length of the text? (For test I've edited what I've extracted with a hex editor)
Btw thank you, I think that a new typetree reader will be really helpful since I've found that for example in the game I'm currently editing all the language text is inside MonoBehaviours. but I didn't find a way to export it if not with raw data.

**Comment by K0lb3** [comment]
It took a bit longer than I thought, anyway, now the update is out.

There are two options now to read and edit MonoBehaviours.

```python
import json

for obj in env.objects:
    if obj.type == "MonoBehaviour":
        # export
        if obj.serialized_type.nodes:
            # save decoded data
            tree = obj.read_typetree()
            fp = os.path.join(extract_dir, f"{data.name}.json"):
            with open(fp, "wt", encoding = "utf8") as f:
                json.dump(tree, f, ensure_ascii = False, indent = 4)
        else:
            # save raw relevant data (without Unity MonoBehaviour header)
            data = obj.read()
            fp = os.path.join(extract_dir, f"{data.name}.bin"):
            with open(fp, "wb") as f:
                f.write(data.raw_data)

        # edit
        if obj.serialized_type.nodes:
            tree = obj.read_typetree()
            # apply modifications to the data within the tree
            obj.save_typetree(tree)
        else:
            with open(replace_dir, data.name) as f:
                data.save(raw_data = f.read())```

In your case with the raw data you can simply use the save function with the kwarg raw_data now.

> Ok perfect, just for info, the alignment should occur even if I don't change the length of the text? (For test I've edited what I've extracted with a hex editor)

If the text length doesn't change then it should work.

**Comment by Nuked88** [comment]
Perfect! I will give it a try today!

**Comment by Nuked88** [comment]
uhm... is not working.
There are 3 issues:
1- if you run your example on the file I'm currently working on and at the end (outside the for loop) you do a  
        with open(os.path.join(root, "file_patched"), "wb") as f:
            f.write(e.file.save())    
     the file salved will be almost the double of the size of the original
2-  that file will be really different from the original, it almost like is a different encoding in some part. 
Look at this image(At the left the Original vs At the left the patched):
![compare](https://user-images.githubusercontent.com/1554140/114226349-c1676680-9973-11eb-918b-a959d6653101.png)

3-  that file has inside almost every MonoBehaviour repeated two times and if you try to save only the MonoBehaviour you have patched in the final file you will not have the edited MonoBehaviour inside but just the original MonoBehaviour repeated two times  (maybe there are some variables that need to be cleared before the save?)

Please be aware that I'm working only with raw data because I cannot extract those file in another way apparently

Thank you for your patience

**Comment by K0lb3** [comment]
> 1- if you run your example on the file I'm currently working on and at the end (outside the for loop) you do a
with open(os.path.join(root, "file_patched"), "wb") as f:
f.write(e.file.save())
the file salved will be almost the double of the size of the original
2- that file will be really different from the original, it almost like is a different encoding in some part.
Look at this image(At the left the Original vs At the right the patched):

[for an explanation read this](https://github.com/K0lb3/UnityPy/issues/42#issuecomment-813037555)

> 3- that file has inside almost every MonoBehaviour repeated two times and if you try to save only the MonoBehaviour you have patched in the final file you will not have the edited MonoBehaviour inside but just the original MonoBehaviour repeated two times (maybe there are some variables that need to be cleared before the save?)

I made a really dumb mistake in the save function....it used self.raw_data instead of the kwarg raw_data.
Coupled with something else I overlooked the data of the monobehaviour was saved two times.

1.7.2 fixes both problems.

at least
```python
        data = obj.read()
        raw = data.raw_data
        data.save(raw_data = bytes(raw).replace(b"4239a5", b"axiome"))
```
works fine with it

**Comment by Nuked88** [comment]
Thank you, now it's working!
