### ISSUE TITLE
MonoBehaviour Treetype Edit

### ISSUE THREAD

**Issue by justtango** [K0lb3/UnityPy#44]
I‘m tring to edit MonoBehaviour by tree type, but it is no effect when I save it with 'save_typetree(tree)'.
I notice the other issue #43, but it can not help me.
Pls help me, this is a great project, best wishes for you.

**Code**
for obj in env.objects:

    if obj.type == 'MonoBehaviour':

        # export
        if obj.serialized_type.nodes:
            tree = obj.read_typetree()

            if name is not None:
                text = tree.get('Text')

                if '学園付近' in text:

                    tree['Text'] = """選抜レースを明日に控えた昼下がり、\n\n学園付近の公園を散歩していると――"""
                    obj.save_typetree(tree)

**Bug**
It is no effect when I save it with 'save_typetree(tree)'. and I try to save it like:
    with open(path + '.txt', 'wb') as f:
        f.write(env.file.save('original'))
**Pls notice that I only change '\t' to '\n' in tree['Text'].**

I will get a ompletely different file.(the Original vs  the changed)
![image](https://user-images.githubusercontent.com/76509288/114518980-7fd80380-9c72-11eb-8f98-94c6e1ffcfa8.png)
![image](https://user-images.githubusercontent.com/76509288/114519001-86667b00-9c72-11eb-9f79-23a4d6c295d5.png)

**To Reproduce**
- following data:
  - Python 3.6
  - UnityPy 1.7.2

**Comment by K0lb3** [comment]
It's a bit hard to judge that from just the screenshots alone.
There can be various reasons for this, with the simplest one being a cause of compression.
The data block info can be compressed, which would cause the difference as the compression levels as well as implementations make a difference.
The file size of edited bundles is usually differed from the original as well because Unity tends to use a lot of big alignments, which UnityPy doesn't. Usually, this doesn't cause a problem.

The big question is, does the game load the asset or not after it was edited?
(with no compression and 'original' compression tested)

**Comment by K0lb3** [comment]
When I developed the typetree editing I also validated it by comparing the edited result with the original in binary data.
There was no mismatch in over 100.000 objects, so at least the typetree editing itself should be fine.
If the game can't load the edited asset, then it's likely related to the bundle structure.

**Comment by justtango** [comment]
> It's a bit hard to judge that from just the screenshots alone.
> There can be various reasons for this, with the simplest one being a cause of compression.
> The data block info can be compressed, which would cause the difference as the compression levels as well as implementations make a difference.
> The file size of edited bundles is usually differed from the original as well because Unity tends to use a lot of big alignments, which UnityPy doesn't. Usually, this doesn't cause a problem.
> 
> The big question is, does the game load the asset or not after it was edited?
> (with no compression and 'original' compression tested)

Thanks for reply!
I tested the game with no compression and 'original / lz4' compression, but only 'no compression' can be loaded.
So, I'm not sure, could there be some other unrecognized compression formats here?

**Comment by K0lb3** [comment]
At least the compression type is safe.
The compression flag might hold additional information like described in [Deep dive into UnityFS](https://www.imbushuo.net/blog/archives/505).
The only question is, how this is implemented.

I don't really have an example to work with atm that refuses to work with the so far implemented formats (copied from UABE),
so I can't really test it myself, but you could try using the following packer/flags.

.save(packer = (x,y))

with x,y being

64,2 (no header compression, lz4 data)
66,2 (lz4 header, lz4 data)
66,66 (same as default, but with additional lz4 compression flags)

**Comment by justtango** [comment]
Sorry for late reply. I test the game as you suggested:
64,2 (no header compression, lz4 data)
66,2 (lz4 header, lz4 data)
66,66 (same as default, but with additional lz4 compression flags)
The "64,2" works well!
Thanks so much!
