### ISSUE TITLE
Sprite-Texture2D merging issue

### ISSUE THREAD

**Issue by szescxz** [K0lb3/UnityPy#45]
**Code**
```Python
import UnityPy
env = UnityPy.load("live_note_default")
for path, obj in env.container.items():
    print(path, obj.type)
````

**Error**
N/A

**Bug**
Seems like the Sprite-Texture2D merging is performed in the wrong direction.
Four `Sprite` in the sample: `notes_crtcl`, `notes_flick`, `notes_long` and `notes_normal`, all based on the `Texture2D` `notes`. (let's ignore the rest of the items here)
I'm expecting all four `Sprite`s in the output, but UnityPy only gives me one `Sprite` named `notes`.

Also a tiny bug, too lazy for a separate issue: 1.7.3 breaks `str(obj.type)`, now all items are `UnknownType`.

**To Reproduce**
- a copy of the file that causes the problem
[live_note_default.zip](https://github.com/K0lb3/UnityPy/files/6326043/live_note_default.zip) (unzip it and you should get an asset bundle file)
- following data:
  - Python version 3.7.3
  - UnityPy version 1.7.2

**Comment by K0lb3** [comment]
A lot of sprites in that asset have the identical container path, so extracting the objects only via the container won't do in this case.
Strictly speaking UnityPy doesn't handle the containers correctly. UnityPy handles them as dict (path -> obj), while they are actually a multi-dict, which can have multiple entries with the same key.

> Also a tiny bug, too lazy for a separate issue: 1.7.3 breaks str(obj.type), now all items are UnknownType.

Thanks for reporting that issue, I pushed a fix for it just now.

**Comment by erikchan002** [comment]
Are there any plans on completing to TODO of fixing the container dictionary for non-unique container paths?

While I understand and can workaround the fact that I cannot access all of the objects via the container, the issue also prevents me from knowing the container path for some of the objects even when the objects are accessed by `env.objects`:
```python
env = UnityPy.load("live_note_default")
path_ids = [-8615770281572025746,-8198049756159249405,-3594623656469114911,310693865538495986,4976375391278443517]
[object.container for object in env.objects if object.path_id in path_ids]
"""
[None,
 'assets/sekai/assetbundle/resources/startapp/live/note/default/textures/notes.png',
 None,
 None,
 None]
"""
```
![image](https://user-images.githubusercontent.com/10881196/188259776-5d316ca3-2557-4a1f-8223-2f6ee5ae461d.png)
<br/>
A simple solution is to just use a dict of list for `self.container_` in `SerializedFile`, `self.m_Container` in `AssetBundle`, the type annotation for `env`, and other places in tools, examples and the readme. e.g. in `SerializedFile.py`
https://github.com/K0lb3/UnityPy/blob/61b03e3eb1b06299cf2296a725bcde0ade629e0a/UnityPy/files/SerializedFile.py#L1
https://github.com/K0lb3/UnityPy/blob/61b03e3eb1b06299cf2296a725bcde0ade629e0a/UnityPy/files/SerializedFile.py#L200
https://github.com/K0lb3/UnityPy/blob/61b03e3eb1b06299cf2296a725bcde0ade629e0a/UnityPy/files/SerializedFile.py#L277-L286 
etc.
<br/>
```python
env = UnityPy.load("live_note_default")
path_ids = [-8615770281572025746,-8198049756159249405,-3594623656469114911,310693865538495986,4976375391278443517]
[object.container for object in env.objects if object.path_id in path_ids]
"""
['assets/sekai/assetbundle/resources/startapp/live/note/default/textures/notes.png',
 'assets/sekai/assetbundle/resources/startapp/live/note/default/textures/notes.png',
 'assets/sekai/assetbundle/resources/startapp/live/note/default/textures/notes.png',
 'assets/sekai/assetbundle/resources/startapp/live/note/default/textures/notes.png',
 'assets/sekai/assetbundle/resources/startapp/live/note/default/textures/notes.png']
"""
```
This however breaks all backwards compatibility for applications currently using containers. 
```python
env.container
"""
{'assets/sekai/assetbundle/resources/startapp/live/note/default/atlas/noteatlas.spriteatlas': [<PPtr <ObjectReader SpriteAtlas>>],
...
"""
```
I can create a PR if there is no WIP on fixing this issue but I do not understand UnityPy fully so there may be other affected places I missed. I know it is very bad to have such a huge break in backwards compatibility but I am just trying to keep this discussion open.

**Comment by K0lb3** [comment]
I'm planning on fixing the issue with UnityPy version 2,
as as you've said, it would break all existing scripts that use the container.

I plan to use either a list of namedtuple or a multidict for the container.

I guess that it would be possible to add a temporary alternative to container,
with container falling back to that alternative to avoid breaking compatibility.
