### ISSUE TITLE
NameError: name 'sp' is not defined in export/ShaderConverter.py

### ISSUE THREAD

**Issue by martinwang2002** [K0lb3/UnityPy#47]
**Code**
https://github.com/K0lb3/UnityPy/blob/4025d10b9575992005d266d89f516739f7653414/UnityPy/export/ShaderConverter.py#L568

**Error**
NameError: name 'sp' is not defined

**Bug**
I suppose this is a typo.
```Python
sb.append(buff.decode("utf8"))
```
After fixing this typo, I encountered AttributeError: 'memoryview' object has no attribute 'decode'. 
```Python
sb.append(buff.tobytes().decode("utf8"))
```
And this fixes.

**To Reproduce**
- An `ab` file from IOS platform may cause this issue.
- following data:
  - Python version 3.8
  - UnityPy version 1.7.6

**Comment by K0lb3** [comment]
Thanks for reporting the typo and the following problem.
