### ISSUE TITLE
How to edit FONT

### ISSUE THREAD

**Issue by justtango** [K0lb3/UnityPy#48]
I want to edit FONT, export, modify and reimport. But it do not work when I save() it:
**Code**
```
env = UnityPy.load(file_path)
    for obj in env.objects:
        if obj.type == 'Font':
           font.m_FontData = open(font_file_path, 'rb').read()
           font.save()
    with open(another_file_path, 'wb') as f:
        f.write(env.file.save())
```

**Error**
The Font do not change. How can I edit a Font file pls?

- following data:
  - Python version: 3.6.0
  - UnityPy version: 1.7.6

**Comment by K0lb3** [comment]
A lot of game use glyphs instead of normal fonts,
in such cases, it's not possible to edit the font data that way.

Exporting, to say nothing about editing, glyph based fonts isn't supported atm yet either,
because it's very difficult to convert them into a normal font, due to the way fonts work.

**Comment by justtango** [comment]
I see. Thanks for reply!
