### ISSUE TITLE
I have a question to ask you.

### ISSUE THREAD

**Issue by SMalls0098** [K0lb3/UnityPy#5]
Ask, in your project. 
Img = Image.frombytes (mode, (width, height), data [0:], codec, args). 
You can turn the content into a picture. Is there any way to turn the picture into content?

**Comment by K0lb3** [comment]
I guess you mean replacing the image(data) of an asset with another one?

I'm working on such a feature atm, but it will still take some time until it's finished.
Changing even one value of an object results in a lot of work that has to be done.

**Comment by SMalls0098** [comment]
Okay, that's a good idea. 
I'm studying your project.
