### ISSUE TITLE
Error calling StreamedClip.ReadData(): list object has no attribute "seek"

### ISSUE THREAD

**Issue by Therhokar** [K0lb3/UnityPy#53]
**Code**
```python
for obj in env.objects:
    if obj.type == 'AnimationClip':
        data = obj.read()
        print(data.m_MuscleClip.m_Clip.m_StreamedClip.ReadData())
```

**Error**
```
Traceback:
  File "classes/AnimationClip.py", line 370, in ReadData
    reader = EndianBinaryReader(buffer)
  File "streams/EndianBinaryReader.py", line 21, in __new__
    obj.__init__(item, endian)
  File "streams/EndianBinaryReader.py", line 217, in __init__
    self.Length = self.stream.seek(0, 2) - offset
AttributeError: 'list' object has no attribute 'seek'
```

**Bug**
`StreamedClip` initializes its `data` attribute by calling `read_u_int_array()`, which returns a list. `ReadData()` passes `data` to `EndianBinaryReader` as stream, whereupon `EndianBinaryReader_Streamable` tries to call `seek()`, which I guess is a method of `IOBase`.

**To Reproduce**
- Problem encountered when working with some Live2D `ab` files from Android
- following data:
  - Python version: 3.9.5
  - UnityPy version: 1.7.6

**Comment by K0lb3** [comment]
Thanks for the notice.

Looks like the implementation of the ReadData function has a bunch of issues, next to the one you already named.
I will work on it in some days when I have some time.

**Comment by K0lb3** [comment]
#54
