### ISSUE TITLE
mod assets question

### ISSUE THREAD

**Issue by w0x12ef** [K0lb3/UnityPy#55]
*******************************************write files to bundle *****************
globalgamemanagers
Resources/unity_builtin_extra
globalgamemanagers.assets
sharedassets0.assets
sharedassets0.assets.resS
level0
sharedassets1.assets
sharedassets1.assets.resS
level1
resources.assets
resources.assets.resS
CAB-UnityPy_Mod.resS
********************************************write files to bundle over **************************
The above is log of the "save " function procedure,  why there is  no   CAB-UnityPy_Mod.assets file written 
 
  - UnityPy version 2019.4.15f1
  - python version 3.8

**Comment by K0lb3** [comment]
Bundle files can include resource files.
The texture2d setter creates such a resource file, if it notices, that the current file is a Bundle file.
This resource file is created within the bundle and not as a real file itself, so it won't show up as an actual file either.

**Comment by w0x12ef** [comment]
Have the unity document mentioned this ? please gives a reference link.

**Comment by K0lb3** [comment]
Sadly there is no real documentation about how the Unity package system works.
It's also one of the aspects which Unity keeps in C++ and not in C#,
so all parser implementations are more or less made up based on the found data and the outputs of decompilers.
