### ISSUE TITLE
Float number parsing & rounding issue

### ISSUE THREAD

**Issue by RaenonX** [K0lb3/UnityPy#69]
Not sure if this is a feature request or a question, but how do I get rid of numbers like `0.1000004`?

I know that in a binary POV, it's impossible to represent `0.1` due to its nature. However, when I was using AssetStudio in C#, for some reason, the exported floats won't have this kind of thing. Python has [`decimal`] class for handling this.

I haven't looked deep into [`decimal`], but my proposal will be to add something like `UnityPy.load(decimal=True)`, so that the user won't run into trouble (or at least expect some) if the interface for [`decimal`] is different.

This fix would be greatly appreciated because I recently switched over from AssetStudio C# custom CLI to this for easier library access. I was doing exact number match in my test cases, but now I have to equip all of them with approx match. This rounding issue could also lead to some inaccurate results.

[`decimal`]: https://docs.python.org/3/library/decimal.html

**Comment by K0lb3** [comment]
Using decimal could result in problems for some asset types, as it can also impact the accuracy of the read and used data.
It's only use might be for some specific asset types, but considering that more often than not the extracted data will be used via script as well, I don't really see the point to include it directly into the library.


As you want to implement it anyway, you can either create a branch of UnityPy and implement the modifications there, or post-process the outputted data, e.g. by parsing it again to a dict, then iterating over all keys and if a float is detected, using decimal on it.

**Comment by RaenonX** [comment]
I currently am actually doing postprocess, but what I found is that the
data I obtained from `read_typetree()` is already loaded (already
1.59999992718…something like this), so I I'll appreciate if you know where
to place my custom loading code because I have no idea where to put it.

I don't get why it impacts the accuracy (IMO decimal is for more precise
arithmetics), could you clarify on this?

Just as a prevention, I do appreciate you work, just bringing up points
that I am not fully understand yet, no offense ;)

**Comment by K0lb3** [comment]
In the case of type trees, you would have to wrap the[ value assignment for float and double in decimal](https://github.com/K0lb3/UnityPy/blob/bc1361faf52ebb6fdc455e4618d2dba5fdcbda39/UnityPy/helpers/TypeTreeHelper.py#L87).
Though, I'm not sure if the JSON module can still dump this.

> I don't get why it impacts the accuracy (IMO decimal is for more precise arithmetics), could you clarify this?

That might be the case if calculations are done with the value, but this isn't the case here. The values are only read from the binary data and nothing else is done with it afterward.  As far as I can see, decimal rounds the values a bit, which might cause problems if one were to load the data via another language or even via python itself.

e.g. with one examples from the issue you referred:
```python
# original
>>> s1 = 0.033333333507180214
# with decimal
>>> s2 = 0.03333333351
>>> s1 == s2
False
```

While the difference is minute, it's still a difference, which would likely spell trouble for stuff like animations.

**Comment by RaenonX** [comment]
Damn, somehow dumb enough not to find it in PEPs. Thanks for helping me find it out. I trust your tests so I think I'll just stick with `.7g` then. Thanks for those helps (and also the fixes) tho!
