### ISSUE TITLE
Import issue with from TypeTreeHelper in Object.py

### ISSUE THREAD

**Issue by Mushymato** [K0lb3/UnityPy#7]
To make obj.dump() work properly, I had to change `from ..helpers import TypeTreeHelper` in `classes/Object.py` to `from ..helpers.TypeTreeHelper import TypeTreeHelper`. I am unsure why this is the case since `helpers/__init__.py` seems to be set up properly.

OS: Windows 10, Python 3.7

**Comment by K0lb3** [comment]
I had this issue somewhere else lately as well and I'm not sure about the cause either.
`from ..helpers.TypeTreeHelper` import TypeTreeHelper` is a good idea and should work in every case.
