### ISSUE TITLE
Texture2DConverter.py Image.tobytes should be img.tobytes

### ISSUE THREAD

**Issue by CChilde** [K0lb3/UnityPy#73]
**Code**
A snippet of the code section that cases the bug or error.
    elif target_texture_format == TF.Alpha8:
        enc_img = Image.tobytes("raw", "A")
        tex_format = TF.Alpha8
    # R
    elif target_texture_format in [
        TF.R8,
        TF.R16,
        TF.RHalf,
        TF.RFloat,
        TF.EAC_R,
        TF.EAC_R_SIGNED,
    ]:
        enc_img = Image.tobytes("raw", "R")
        tex_format = TF.R8
    # RGBA
    elif target_texture_format in [
        TF.RGB565,
        TF.RGB24,
        TF.RGB9e5Float,
        TF.PVRTC_RGB2,
        TF.PVRTC_RGB4,
        TF.ATC_RGB4,
    ]:
        enc_img = Image.tobytes("raw", "RGB")
        tex_format = TF.RGB24

**Error**
The error message that is produced by python.
Image.tobytes("raw", "xxx")  -> img.tobytes("raw", "xxx")

**Bug**
A description of what you expect to happen/see and what actually happens.

**To Reproduce**
- a copy of the file that causes the problem
- following data:
  - Python version
  - UnityPy version

**Comment by K0lb3** [comment]
Thanks for mentioning the issue.
Fix will be out in a bit.
