### ISSUE TITLE
How to get the image data from `Material` @ 1.7.27?

### ISSUE THREAD

**Issue by RaenonX** [K0lb3/UnityPy#78]
I was able to get `PIL.Image` by calling something like `material.image`. However, it's now giving the error: `AttributeError: 'NodeHelper' object has no attribute 'image_data'`.

The current version I am using is `1.7.27`.

> Confirmed issue occurred between `1.7.19` and `1.7.20` - working normally on 19 but not 20.

**Comment by K0lb3** [comment]
Materials have no image property.
Only Texture2Ds and Sprites do so.

According to your error the "Material" you mention seems to be a Texture2D and apparently the parsing of it failed,
as image_data couldn't be accessed.

Can you send an affected asset where this problem occurs?

**Comment by RaenonX** [comment]
> Materials have no image property. Only Texture2Ds and Sprites do so.
> 
> According to your error the "Material" you mention seems to be a Texture2D and apparently the parsing of it failed, as image_data couldn't be accessed.
> 
> Can you send an affected asset where this problem occurs?

Oh, it turns out that it was because I was using `obj.type == "Material"` for filtering the assets, and this no longer works after `1.7.20`. Changing `obj.type` to `obj.type.name` seems fixed the problem. Thanks!
