### ISSUE TITLE
a problem

### ISSUE THREAD

**Issue by 805557409** [K0lb3/UnityPy#79]
Excuse me, I unpacked a mobile game of Unity. I want to try to extract animation from the game. I selected animator and AnimationCilp with AssetStudios and exported them, but the extraction of animation failed. It seems that it needs to use Unity's Animation Retargeting. Can unitypy do that? Thanks!

**Comment by K0lb3** [comment]
UnityPy can't export AnimationClips or other objects that rely on fbx for the export.
It might be added some time, but not any time soon due to the required amount of work.

**Comment by 805557409** [comment]
> UnityPy can't export AnimationClips or other objects that rely on fbx for the export. It might be added some time, but not any time soon due to the required amount of work.

Do you know how to extract some animations that need unity's animation retargeting? I can't seem to find an animator corresponding to animationcilp.
