### ISSUE TITLE
Some questions about MonoBehaviour reading typetree

### ISSUE THREAD

**Issue by ablegao** [K0lb3/UnityPy#85]
**Code**

    from UnityPy import Environment,load
    from UnityPy.files import *
    from UnityPy.classes import  *
    from UnityPy.enums.ClassIDType import ClassIDType
    # This nodes I exported using TypeTreeGeneratorCLI.
    nodes = [{'type': 'MonoBehaviour', 'name': 'Base', 'meta_flag': 0, 'level': 0},
             {'type': 'PPtr<GameObject>', 'name': 'm_GameObject', 'meta_flag': 0, 'level': 1},
             {'type': 'int', 'name': 'm_FileID', 'meta_flag': 0, 'level': 2},
             {'type': 'int', 'name': 'm_PathID', 'meta_flag': 0, 'level': 2},
             {'type': 'UInt8', 'name': 'm_Enabled', 'meta_flag': 16384, 'level': 1},
             {'type': 'PPtr<MonoScript>', 'name': 'm_Script', 'meta_flag': 0, 'level': 1},
             {'type': 'int', 'name': 'm_FileID', 'meta_flag': 0, 'level': 2},
             {'type': 'int', 'name': 'm_PathID', 'meta_flag': 0, 'level': 2},
             {'type': 'string', 'name': 'm_Name', 'meta_flag': 0, 'level': 1},
             {'type': 'Array', 'name': 'Array', 'meta_flag': 16384, 'level': 2},
             {'type': 'int', 'name': 'size', 'meta_flag': 0, 'level': 3},
             {'type': 'char', 'name': 'data', 'meta_flag': 0, 'level': 3},
             {'type': 'PPtr<UiButton>', 'name': 'OkButton', 'meta_flag': 0, 'level': 1},
             {'type': 'int', 'name': 'm_FileID', 'meta_flag': 0, 'level': 2},
             {'type': 'int', 'name': 'm_PathID', 'meta_flag': 0, 'level': 2}]
    
    if __name__ == "__main__":
        env = load("7dc377eeba7a3442d9aaa477b3fc22a0")
        item:MonoBehaviour = None
        for item in env.objects:
            if item.type == ClassIDType.MonoBehaviour:
                item.read_typetree(nodes)

**Error**

UnityPy-1.7.34-py3.9.egg/UnityPy/helpers/TypeTreeHelper.py", line 144, in read_typetree
    raise TypeTreeError(
UnityPy.exceptions.TypeTreeError: Error while read type, read 3928 bytes but expected 136 bytes

 
**To Reproduce**

- following data:
  - python 3.9
  - UnityPy  master

**Comment by K0lb3** [comment]
You have to make sure that the nodes you're trying to use are the correct ones for the specific MonoBehaviour.
You can check that be taking a look at the referenced script.

See [here](https://github.com/K0lb3/UnityPy/blob/17d67e59a4e9316948d94f6db95caf8f3b6ebc93/UnityPy/tools/extractor.py#L190)

**Comment by ablegao** [comment]
Well.... I found the problem, all "m_PathID" exported by TypeTreeGenerator is int , when I change it to UInt64, the problem is gone!

**Comment by ablegao** [comment]
My bad, TypeTreeGenerator has a -v

**Comment by K0lb3** [comment]
Oh, right, I completely forgot about the versioning of the generator.
I guess that I should add a mention about it to the generator repo.
