### ISSUE TITLE
Mesh default export extension should be obj instead of obf

### ISSUE THREAD

**Issue by martinwang2002** [K0lb3/UnityPy#87]
**Code**

https://github.com/K0lb3/UnityPy/blob/17d67e59a4e9316948d94f6db95caf8f3b6ebc93/UnityPy/tools/extractor.py#L157-L162

**Bug**
The Mesh object should export the file with extension `.obj`. I think this is a typo.

This is what it looks like in AssetStudio

https://github.com/Perfare/AssetStudio/blob/0e1a886e0b1bae9d3e990b7b686e10f1c105e65d/AssetStudioGUI/Exporter.cs#L127-L133

**Comment by K0lb3** [comment]
You're right, it should be ``.obj``.
Thanks for mentioning the issue.
