### ISSUE TITLE
A good solution

### ISSUE THREAD

**Issue by ablegao** [K0lb3/UnityPy#96]
This maybe a good solution, Just enter assets/bin/Data.
    
    class EnvironmentExt(Environment):
        def __init__(self,dataDir):
            super(EnvironmentExt, self).__init__() 
            self.path = dataDir
            dataUnity3d = os.path.join(dataDir,"data.unity3d")
            if os.path.exists(dataUnity3d):
                self.load_files([dataUnity3d])
            else:
                files = []
                for root,dirName,filex in os.walk(dataDir):
                    if root != dataDir:
                        continue
                    for f in filex:
                        files.append(os.path.join(root,f))
                splits = []
                i=0
                while i < len(files):
                    path = files[i]
                    splitMatch = reSplitFile.match(path)
                    if reSplitFile.match(path):
                        name = splitMatch[1]
                        if name not in splits:
                            splits.append(name)
                        files.remove(path)
                    else:
                        i += 1
    
                # merge splits
                for basepath in splits:
                    # merge data
                    data = io.BytesIO()
                    for i in range(0, 999):
                        item = f"{basepath}.split{i}"
                        if os.path.exists(item):
                            with open(item, "rb") as f:
                                data.write(f.read())
                        else:
                            break
                    self.files[self.reduce_path(basepath)] = self.load_file(data)
                for f in files:
                    if f.endswith(".resource") \
                            or f.endswith(".config") \
                            or f.endswith(".bak") \
                            or f.endswith(".json"):
                        continue
                    op = open(f,"rb")
                    key = self.reduce_path(f)
                    self.files[key] = self.load_file(op)
                for f in self.files:
                    self.register_cab(f,self.files[f])
    
                # self.load_files(newfiles)
                # for i in self.files:
                #     print(i)
                #     self.register_cab(i,self.files[i])
        @property
        def UnityVersion(self)->str:
            if "data.unity3d" in self.files:
                return self.files["data.unity3d"].version_engine
            elif "globalgamemanagers.assets" in self.files:
                return self.files["globalgamemanagers"].version

**Comment by K0lb3** [comment]
I'm not really sure what you want to say with this.
Using code for only specific files isn't really a good solution at the very least.
